# Generated by Django 4.0.5 on 2022-06-17 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_datecreated_product_dateupdated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='dateUpdated',
            new_name='lastUpdated',
        ),
    ]
