# Generated by Django 4.0.5 on 2022-06-17 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_dateupdated_product_lastupdated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='coverImage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_cover_image', to='product.productimage'),
        ),
    ]
