# Generated by Django 4.0.5 on 2022-06-17 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_coverimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
