# Generated by Django 4.0.5 on 2022-06-17 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='report_doctor', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='report_patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/reports')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_file_report', to='report.report')),
            ],
        ),
    ]
