# Generated by Django 4.0.5 on 2022-06-17 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_username_user_datecreated_user_lastlogin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='isActivated',
        ),
    ]
