# Generated by Django 4.0.5 on 2022-07-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogpost_word_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='similarity',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
