# Generated by Django 4.0.5 on 2022-06-16 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_remove_prescription_files_remove_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.RemoveField(
            model_name='report',
            name='files',
        ),
    ]
