# Generated by Django 4.0.5 on 2022-06-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_alter_user_lastlogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='profile/avatar.png', null=True, upload_to='profile'),
        ),
    ]
