# Generated by Django 4.0.5 on 2022-06-08 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='files',
            field=models.FileField(null=True, upload_to='attachments/prescriptions'),
        ),
    ]
