# Generated by Django 4.0.5 on 2022-06-08 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_alter_prescription_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='attachments/prescriptions'),
        ),
    ]
