# Generated by Django 4.0.5 on 2022-06-08 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_alter_prescription_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='type',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
